### ISSUE TITLE
Utils tests fail on master

### ISSUE THREAD

**Issue by metaspace** [westerndigitalcorporation/zenfs#151]
When running
```shell
bash -c "ZDEV=${DEVICE} FS_PARAMS=--fs_uri=zenfs://dev:${DEVICE} TOOLS_DIR=/rocks/dest/bin ZENFS_DIR=/rocks/dest/bin OUTPUT_DIR=/rocks/work/results /rocks/dest/zenfs/test/run.sh ci utils"
```
0050_restore.sh fails.

stdout:
```shell
ZenFS file system created. Free space: 971454 MB
Running utils/0010_mkfs.sh

Test duration 0h 0m 1s
OK
Running utils/0020_list.sh

Test duration 0h 0m 11s
OK
Running utils/0030_df.sh

Test duration 0h 0m 0s
OK
Running utils/0040_backup.sh
List reported 9 files, backup dir is /rocks/work/results/ci/utils/backup

Test duration 0h 0m 32s
OK
Running utils/0050_restore.sh

Test duration 0h 0m 3s
FAILED

1 TESTS FAILED
Test set duration 0h 0m 47s
```

stderr:
```shell
RocksDB:    version 6.25
Date:       Sat Feb  5 15:29:10 2022
CPU:        32 * AMD EPYC-Rome Processor
CPUCache:   512 KB
Failed: Can't parse file type:
```

**Comment by aravind-wdc** [comment]
This issue is not seen with latest rocksdb master and zenfs master.

$ sudo FS_PARAMS="--fs_uri=zenfs://dev:nullb1" ZDEV=nullb1 ./run.sh util-tests utils
Running utils/0010_mkfs.sh 

Test duration 0h 0m 0s
OK
Running utils/0020_list.sh 
RocksDB:    version 7.0
Date:       Tue Feb 22 11:13:40 2022
CPU:        32 * AMD EPYC 7302P 16-Core Processor
CPUCache:   512 KB
... finished 1000000 ops
Test duration 0h 0m 8s
OK
Running utils/0030_df.sh 

Test duration 0h 0m 0s
OK
Running utils/0040_backup.sh 
List reported 9 files, backup dir is results/util-tests/utils/backup

Test duration 0h 0m 15s
OK
Running utils/0050_restore.sh 

Test duration 0h 0m 14s
OK

ALL TESTS PASSED
Test set duration 0h 0m 37s
Test set output available at results/util-tests/utils
